controller_manager:
  ros parameters:
    update rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    # gripper_controller:
    #   type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros_parameters:
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true



gripper_controller:
  ros_parameters:
    joints:
    - joint6

    # interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true